---
title: "558_Project1_Hunter"
author: "Samantha Hunter"
date: "9/24/2021"
output: html_document
---

```{r}
library(httr)
library(jsonlite)
library(purrr)
library(dplyr)
library(tibble)

# map function
library(purrr)

# ldply function
library(plyr)
```

# Endpoint 1 - Ability - Join Tibbles!
```{r}
# Endpoint 1
#Here is an entire list of pokemon ability names
avail_ability <- GET("https://pokeapi.co/api/v2/ability/?limit=327&offset=0")
avail_ability <- rawToChar(avail_ability$content)
avail_ability <- fromJSON(avail_ability)
avail_ability <- avail_ability[["results"]][["name"]]

ability <- function(name, ...){
  url_ability <- paste0("https://pokeapi.co/api/v2/ability/", c(name, ...))
  poke_bility <- lapply(url_ability, GET)
  poke_bility<-lapply(poke_bility, '[[', 'content')
  poke_bility <- lapply(poke_bility, rawToChar)
  poke_bility <- lapply(poke_bility, fromJSON)
}

abilities <- (map(poke_bility, "name"))
ability_pokemon <- (map(map(map(poke_bility, "pokemon"), "pokemon"), "name"))
ability_generation <- map(map(poke_bility, "generation"), "name")

# probs needs to be Pokemon_Ability <- list(rep(0, length(abilities)))
Pokemon_Ability <- list(rep(0, 5))
for(a in 1:5){
  ab_pokemon <- unlist(ability_pokemon[a])
  ab <- rep(abilities[a], length(ability_pokemon[a]))
  ab_gen <- rep(ability_generation[a], length(ability_pokemon[a]))
  Pokemon_Ability[[a]] <- as.tibble(cbind(ab_pokemon, ab, ab_gen))
}

# THIS WORKS :)
stench <- ability("stench", "drizzle")

# https://stackoverflow.com/questions/47254147/how-to-convert-multiple-lists-into-one-dataframer t

#battle_effect <- map(map(poke_bility, "effect_entries"), "effect")
#poke_bility[[1]][["effect_changes"]][["effect_entries"]][[1]][["effect"]][[2]]

```


# Endpoint 2 - Pokemon Type _ Join Tibbles!
```{r}
# Endpoint 3 - there are 20 possible types 
avail_types <- GET("https://pokeapi.co/api/v2/type/?limit=20&offset=0")
avail_types <- rawToChar(avail_types$content)
avail_types <- fromJSON(avail_types)
avail_types <- avail_types[["results"]][["name"]]

type <- function(name, ...){
  url_type <- paste0("https://pokeapi.co/api/v2/type/", c(name, ...))
  poke_type <- lapply(url_type, GET)
  poke_type <-lapply(poke_type, '[[', 'content')
  poke_type <- lapply(poke_type, rawToChar)
  poke_type <- lapply(poke_type, fromJSON)
  return(poke_type)
}

remove(no_to)

type <- map(poke_type, "name")
type_pokemon <- map(map(map(poke_type, "pokemon"), "pokemon"), "name")
type_double_from <- map(map(map(poke_type, "damage_relations"), "double_damage_from"), "name")
type_half_from <- map(map(map(poke_type, "damage_relations"), "half_damage_from"), "name")
type_no_from <- map(map(map(poke_type, "damage_relations"), "no_damage_from"), "name")
type_double_to <- map(map(map(poke_type, "damage_relations"), "double_damage_to"), "name")
type_half_to <- map(map(map(poke_type, "damage_relations"), "half_damage_to"), "name")
type_no_to <- map(map(map(poke_type, "damage_relations"), "no_damage_to"), "name")

Pokemon_Type <- list(rep(0, 5))
for(a in 1:5){
  pokemon <- unlist(type_pokemon[a])
  type <- rep(type[a], length(type_pokemon[a]))
  double_from <- rep(type_double_from[a], length(type_pokemon[a]))
  double_to <- rep(type_double_to[a], length(type_pokemon[a]))
  half_from <- rep(type_half_from[a], length(type_pokemon[a]))
  half_to <- rep(type_half_to[a], length(type_pokemon[a]))
  no_from <- rep(type_no_from[a], length(type_pokemon[a]))
  no_to <- rep(type_no_to[a], length(type_pokemon[a]))
  
  Pokemon_Type[[a]] <- as.tibble(cbind(pokemon, type, double_from, 
                                    double_to, half_from, half_to, 
                                    no_from, no_to))
}

```

# Endpoint 3 - Region - Join Tibbles! 
```{r}
# Pokemon Region - there are 8 of them
avail_region <- GET("https://pokeapi.co/api/v2/region/?limit=20&offset=0")
avail_region <- rawToChar(avail_region$content)
avail_region <- fromJSON(avail_region)
avail_region <- avail_region[["results"]][["name"]]

region <- function(name, ...){
  url_region <- paste0("https://pokeapi.co/api/v2/region/", c(name, ...))
  poke_region <- lapply(url_region, GET)
  poke_region <- lapply(poke_region, '[[', 'content')
  poke_region <- lapply(poke_region, rawToChar)
  poke_region <- lapply(poke_region, fromJSON)
  return(poke_region)
}

regions <- map(poke_region, "name")
regions_loc <- map(map(poke_region, "locations"), "name")
region_gen <- map(map(poke_region, "main_generation"), "name")
region_game <- map(map(poke_region, "version_groups"), "name")

Pokemon_Regions <- list(rep(0, 5))
for(a in 1:5){
  locations <- unlist(regions_loc[a])
  region <- rep(regions[a], length(regions_loc[a]))
  region_gen <- rep(region_gen[a], length(regions_loc[a]))
  region_game <- rep(region_game[a], length(regions_loc[a]))
  Pokemon_Regions[[a]] <- as.tibble(cbind(region, locations,
                                      region_gen, region_game))
}
```


Make function & turn into one data frame
```{r}
avail_gen <- GET("https://pokeapi.co/api/v2/generation/")
avail_gen <- rawToChar(avail_gen$content)
avail_gen <- fromJSON(avail_gen)
avail_gen <- avail_gen[["results"]][["name"]]

url_gen <- paste0("https://pokeapi.co/api/v2/generation/", c(avail_gen))
poke_gen <- lapply(url_gen, GET)
poke_gen <- lapply(poke_gen, '[[', 'content')
poke_gen <- lapply(poke_gen, rawToChar)
poke_gen <- lapply(poke_gen, fromJSON)

gen <- map(poke_gen, "name")
gen_poke <- map(map(poke_gen, "pokemon_species"), "name")

Pokemon_Generation <- list(rep(0, 5))
for(a in 1:5){
  pokemon <- unlist(gen_poke[a])
  generation <- rep(gen[a], length(gen_poke[a]))
  Pokemon_Generation[[a]] <- as.tibble(cbind(generation, pokemon))
}
```


# Endpoint 4 - Habitat
```{r}
# Endpoint2 - Pokemon Habitat, if you want all 9 habitats, you can also use 1:9
# I've attached these next lines in case you don't know what habitats are available
# for querying
avail_habitat <- GET("https://pokeapi.co/api/v2/pokemon-habitat/?limit=20&offset=0")
avail_habitat <- rawToChar(avail_habitat$content)
avail_habitat <- fromJSON(avail_habitat)
avail_habitat <- avail_habitat[["results"]][["name"]]

habitat <- function(name, ...){
  url_habitat <- paste0("https://pokeapi.co/api/v2/pokemon-habitat/", c(name, ...))
  poke_habitat <- lapply(url_habitat, GET)
  poke_habitat <-lapply(poke_habitat, '[[', 'content')
  poke_habitat <- lapply(poke_habitat, rawToChar)
  poke_habitat <- lapply(poke_habitat, fromJSON)
  return(poke_habitat)
}

habitat <- map(poke_habitat, "name")
habitat_poke <- map(map(poke_habitat, "pokemon_species"), "name")

Pokemon_Habitat <- list(rep(0, 5))
for(a in 1:5){
  pokemon <- unlist(habitat_poke[a])
  hab <- rep(habitat[a], length(habitat_poke[a]))
  Pokemon_Habitat[[a]] <- as.tibble(cbind(hab, pokemon))
}
```




# Endpoint 5 - Berries - HAVE TIBBLE OUTPUT
```{r}
# There are 64 Berry Types
avail_berry <- GET("https://pokeapi.co/api/v2/berry?offset=0&limit=200")
avail_berry <- rawToChar(avail_berry$content)
avail_berry <- fromJSON(avail_berry)
avail_berry <- avail_berry[["results"]][["name"]]

berry <- function(name, ...){
  url_berry <- paste0("https://pokeapi.co/api/v2/berry/", c(name, ...))
  poke_berry <- lapply(url_berry, GET)
  poke_berry <- lapply(poke_berry, '[[', 'content')
  poke_berry <- lapply(poke_berry, rawToChar)
  poke_berry <- lapply(poke_berry, fromJSON)
  
  berries <- unlist(map(poke_berry, "name"))
  growth_time <- unlist(map(poke_berry, "growth_time"))
  max_harvest <- unlist(map(poke_berry, "max_harvest"))

  Pokemon_Berry <- as_tibble(cbind(berries, growth_time, max_harvest))
  return(Pokemon_Berry)
}

# It works
berry("cheri", "chesto")
```


# Endpoint 6 - Pokemon Base Stats (from Pokemon) - DATA FRAME ACQUIRED
```{r}
# this produces duplicates of the same pokemon, there are 1188 available pokemon
# include in the function a way to supply the pokemon name, then make it correspond to 
# the indexing number
avail_pokemon <- GET("https://pokeapi.co/api/v2/pokemon/?limit=1200&offset=0")
avail_pokemon <- rawToChar(avail_pokemon$content)
avail_pokemon <- fromJSON(avail_pokemon)
avail_pokemon <- avail_pokemon[["results"]][["name"]]


poke_stats <- function(name, ...){
  url <- paste0("https://pokeapi.co/api/v2/pokemon/",c(name, ...))
  pokedex <- lapply(X = url, FUN = GET)
  pokedex<-lapply(pokedex, '[[', 'content')
  pokedex <- lapply(pokedex, rawToChar)
  pokedex <- lapply(pokedex, fromJSON)
  
  pokemon_stat <- map(pokedex, "name")
  base_stat <- map(map(pokedex, "stats"), "base_stat")

  poke_statly <- rep(0, length(pokemon_stat))
  hp <- rep(0, length(pokemon_stat))
  attack  <- rep(0, length(pokemon_stat))
  defense <- rep(0, length(pokemon_stat))
  sp_attack <- rep(0, length(pokemon_stat))
  sp_defense <- rep(0, length(pokemon_stat))
  speed <- rep(0, length(pokemon_stat))

  for(p in 1:length(pokemon_stat)){
    poke_statly[p] <- pokemon_stat[[p]]
    hp[p] <- base_stat[[p]][1]
    attack[p]  <- base_stat[[p]][2]
    defense[p] <- base_stat[[p]][3]
    sp_attack[p] <- base_stat[[p]][4]
    sp_defense[p] <- base_stat[[p]][5]
    speed[p] <- base_stat[[p]][6]
  }
  Pokemon_Stats <- as_tibble(cbind(poke_statly, hp, attack, defense, sp_attack, sp_defense, speed))
  return(Pokemon_Stats)
}

poke_stats(1:400)
```


```{r}

```











